#ifndef ACTION_H
#define ACTION_H

#include <lily/action.h>

/* Import the Lily namespace. */

#define NO_COMPARE LILY_ACTION_NO_COMPARE
#define EQUAL LILY_ACTION_EQUAL

#define INPUT LILY_ACTION_INPUT
#define OUTPUT LILY_ACTION_OUTPUT
#define INTERNAL LILY_ACTION_INTERNAL

#define NO_PARAMETER LILY_ACTION_NO_PARAMETER
#define PARAMETER LILY_ACTION_PARAMETER
#define AUTO_PARAMETER LILY_ACTION_AUTO_PARAMETER

#endif /* ACTION_H */
