#ifndef LILY_ACTION_H
#define LILY_ACTION_H

#include <lily/quote.h>

#define LILY_ACTION_INPUT 0
#define LILY_ACTION_OUTPUT 1
#define LILY_ACTION_INTERNAL 2

#define LILY_ACTION_NO_PARAMETER 0
#define LILY_ACTION_PARAMETER 1
#define LILY_ACTION_AUTO_PARAMETER 2

#endif /* LILY_ACTION_H */


