#ifndef LILY_ACTION_H
#define LILY_ACTION_H

#include <lily/quote.h>

#define LILY_ACTION_INPUT 0
#define LILY_ACTION_OUTPUT 1
#define LILY_ACTION_INTERNAL 2
#define LILY_ACTION_SYSTEM_INPUT 3

#define LILY_ACTION_NO_PARAMETER 0
#define LILY_ACTION_PARAMETER 1
#define LILY_ACTION_AUTO_PARAMETER 2

#define LILY_ACTION_AUTO_MAP 1

#define LILY_ACTION_NO_ACTION 0
#define LILY_ACTION_INIT -1

#endif /* LILY_ACTION_H */


