#ifndef LILY_SYSCALL_H
#define LILY_SYSCALL_H

/* Constants. */
#define LILY_SYSCALL_FINISH_NO 0
#define LILY_SYSCALL_FINISH_YES 1
#define LILY_SYSCALL_FINISH_DESTROY 2

/* System calls. */
#define LILY_SYSCALL_FINISH 0

#define LILY_SYSCALL_CREATE 1
#define LILY_SYSCALL_BIND 2
#define LILY_SYSCALL_LOOSE 3
#define LILY_SYSCALL_DESTROY 4
#define LILY_SYSCALL_EXIT 5

#define LILY_SYSCALL_SUBSCRIBE 6

#define LILY_SYSCALL_SBRK 8

#define LILY_SYSCALL_SYSCONF 9
  
#define LILY_SYSCALL_BUFFER_CREATE 10
#define LILY_SYSCALL_BUFFER_COPY 11
#define LILY_SYSCALL_BUFFER_GROW 12
#define LILY_SYSCALL_BUFFER_APPEND 13
#define LILY_SYSCALL_BUFFER_ASSIGN 14
#define LILY_SYSCALL_BUFFER_MAP 15
#define LILY_SYSCALL_BUFFER_UNMAP 16
#define LILY_SYSCALL_BUFFER_DESTROY 17
#define LILY_SYSCALL_BUFFER_CAPACITY 18

#define LILY_SYSCALL_MAP 19
#define LILY_SYSCALL_UNMAP 20

#define LILY_SYSCALL_RESERVE_PORT 21
#define LILY_SYSCALL_UNRESERVE_PORT 22
#define LILY_SYSCALL_INB 23
#define LILY_SYSCALL_OUTB 24

/* Names for sysconf. */
#define LILY_SYSCALL_SYSCONF_PAGESIZE 0

/* Error codes. */
#define LILY_SYSCALL_ESUCCESS 0
#define LILY_SYSCALL_EPERM 1
#define LILY_SYSCALL_EINVAL 2
#define LILY_SYSCALL_ESRCNA 3
#define LILY_SYSCALL_ESRCINUSE 4
#define LILY_SYSCALL_EDSTINUSE 5
#define LILY_SYSCALL_EBADBD 6
#define LILY_SYSCALL_ENOMEM 7
#define LILY_SYSCALL_EBDDNE 8
#define LILY_SYSCALL_EBDSIZE 9
#define LILY_SYSCALL_EALIGN 10
#define LILY_SYSCALL_ESIZE 11
#define LILY_SYSCALL_EBADANO 12
#define LILY_SYSCALL_EPORTINUSE 13
#define LILY_SYSCALL_EAIDDNE 14

#endif /* LILY_SYSCALL_H */
