#ifndef LILY_SYSCALL_H
#define LILY_SYSCALL_H

/* System calls. */
#define LILY_SYSCALL_FINISH 0

#define LILY_SYSCALL_CREATE 1
#define LILY_SYSCALL_BIND 2
#define LILY_SYSCALL_LOOSE 3
#define LILY_SYSCALL_DESTROY 4

#define LILY_SYSCALL_BINDING_COUNT 5  

#define LILY_SYSCALL_SBRK 6
  
#define LILY_SYSCALL_BUFFER_CREATE 7
#define LILY_SYSCALL_BUFFER_COPY 8
#define LILY_SYSCALL_BUFFER_GROW 9
#define LILY_SYSCALL_BUFFER_APPEND 10
#define LILY_SYSCALL_BUFFER_ASSIGN 11
#define LILY_SYSCALL_BUFFER_MAP 12
#define LILY_SYSCALL_BUFFER_UNMAP 13
#define LILY_SYSCALL_BUFFER_DESTROY 14
#define LILY_SYSCALL_BUFFER_SIZE 15

#define LILY_SYSCALL_MAP 16

/* Error codes. */
#define LILY_SYSCALL_ESUCCESS 0
#define LILY_SYSCALL_EPERM 1
#define LILY_SYSCALL_EINVAL 2
#define LILY_SYSCALL_EADDRNOTAVAIL 3
#define LILY_SYSCALL_EADDRINUSE 4
#define LILY_SYSCALL_EBADBID 5
#define LILY_SYSCALL_ENOMEM 6

#endif /* LILY_SYSCALL_H */
