#ifndef LILY_SYSCALL_H
#define LILY_SYSCALL_H

/* System calls. */
#define LILY_SYSCALL_FINISH 0

#define LILY_SYSCALL_CREATE 1
#define LILY_SYSCALL_BIND 2
#define LILY_SYSCALL_LOOSE 3
#define LILY_SYSCALL_DESTROY 4
#define LILY_SYSCALL_EXIT 5

#define LILY_SYSCALL_BINDING_COUNT 6

#define LILY_SYSCALL_SBRK 7
  
#define LILY_SYSCALL_BUFFER_CREATE 8
#define LILY_SYSCALL_BUFFER_COPY 9
#define LILY_SYSCALL_BUFFER_GROW 10
#define LILY_SYSCALL_BUFFER_APPEND 11
#define LILY_SYSCALL_BUFFER_ASSIGN 12
#define LILY_SYSCALL_BUFFER_MAP 13
#define LILY_SYSCALL_BUFFER_UNMAP 14
#define LILY_SYSCALL_BUFFER_DESTROY 15
#define LILY_SYSCALL_BUFFER_SIZE 16

#define LILY_SYSCALL_MAP 17
#define LILY_SYSCALL_UNMAP 18

#define LILY_SYSCALL_SYSCONF 19

/* Names for sysconf. */
#define LILY_SYSCALL_SYSCONF_PAGESIZE 0

/* Error codes. */
#define LILY_SYSCALL_ESUCCESS 0
#define LILY_SYSCALL_EPERM 1
#define LILY_SYSCALL_EINVAL 2
#define LILY_SYSCALL_ESRCRANGE 3
#define LILY_SYSCALL_ESRCINUSE 4
#define LILY_SYSCALL_EDSTINUSE 5
#define LILY_SYSCALL_EBADBID 6
#define LILY_SYSCALL_ENOMEM 7

#endif /* LILY_SYSCALL_H */
